"""add processed column to raw_events

Revision ID: 1f06044b030d
Revises: 495baf4975c6
Create Date: 2026-06-09 18:18:08.333177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f06044b030d'
down_revision: Union[str, Sequence[str], None] = '495baf4975c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_events', sa.Column('processed', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('raw_events', 'processed', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_events', 'processed')
    # ### end Alembic commands ###
