"""add image fields to raw_events

Revision ID: 3af8c67bd054
Revises: 93c26c8d3c94
Create Date: 2026-06-10 17:11:10.559070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3af8c67bd054'
down_revision: Union[str, Sequence[str], None] = '93c26c8d3c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_events', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('raw_events', sa.Column('has_image', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('raw_events', 'has_image', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_events', 'has_image')
    op.drop_column('raw_events', 'image_url')
    # ### end Alembic commands ###
