"""add indexes to events and raw_events

Revision ID: 495baf4975c6
Revises: fc4d56243fc7
Create Date: 2026-06-08 19:37:57.531863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '495baf4975c6'
down_revision: Union[str, Sequence[str], None] = 'fc4d56243fc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_events_event_date'), 'events', ['event_date'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_match_id'), 'events', ['match_id'], unique=False)
    op.create_index(op.f('ix_events_source_url'), 'events', ['source_url'], unique=False)
    op.create_index(op.f('ix_events_teams'), 'events', ['teams'], unique=False)
    op.create_index(op.f('ix_raw_events_source_url'), 'raw_events', ['source_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_events_source_url'), table_name='raw_events')
    op.drop_index(op.f('ix_events_teams'), table_name='events')
    op.drop_index(op.f('ix_events_source_url'), table_name='events')
    op.drop_index(op.f('ix_events_match_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_event_date'), table_name='events')
    # ### end Alembic commands ###
