"""add event_end_date to events

Revision ID: 93c26c8d3c94
Revises: 1f06044b030d
Create Date: 2026-06-09 22:21:46.214377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93c26c8d3c94'
down_revision: Union[str, Sequence[str], None] = '1f06044b030d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_end_date', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'event_end_date')
    # ### end Alembic commands ###
