"""create initial tables

Revision ID: dacabb847c12
Revises: 
Create Date: 2026-06-07 17:32:48.108137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dacabb847c12'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('match_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_football_id', sa.BigInteger(), nullable=True),
    sa.Column('tournament', sa.String(length=100), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('home_team', sa.String(length=100), nullable=True),
    sa.Column('away_team', sa.String(length=100), nullable=True),
    sa.Column('match_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('match_id'),
    sa.UniqueConstraint('api_football_id')
    )
    op.create_table('pipeline_runs',
    sa.Column('pipeline_run_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('events_scraped', sa.Integer(), nullable=False),
    sa.Column('events_processed', sa.Integer(), nullable=False),
    sa.Column('events_rejected', sa.Integer(), nullable=False),
    sa.Column('events_merged', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pipeline_run_id')
    )
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('event_name', sa.String(length=300), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('venue', sa.String(length=300), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('event_date', sa.String(length=20), nullable=True),
    sa.Column('event_time', sa.String(length=20), nullable=True),
    sa.Column('teams', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('event_type_confidence', sa.Float(), nullable=True),
    sa.Column('venue_confidence', sa.Float(), nullable=True),
    sa.Column('team_confidence', sa.Float(), nullable=True),
    sa.Column('is_duplicate_candidate', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('raw_events',
    sa.Column('raw_event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.pipeline_run_id'], ),
    sa.PrimaryKeyConstraint('raw_event_id')
    )
    op.create_table('raw_event_contributions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raw_event_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['raw_event_id'], ['raw_events.raw_event_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_event_contributions')
    op.drop_table('raw_events')
    op.drop_table('events')
    op.drop_table('pipeline_runs')
    op.drop_table('matches')
    # ### end Alembic commands ###
