"""add balldontlie_id to matches

Revision ID: fc4d56243fc7
Revises: dacabb847c12
Create Date: 2026-06-07 18:58:19.512280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc4d56243fc7'
down_revision: Union[str, Sequence[str], None] = 'dacabb847c12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('balldontlie_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'matches', ['balldontlie_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches', type_='unique')
    op.drop_column('matches', 'balldontlie_id')
    # ### end Alembic commands ###
